// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/enrollment.proto

package enrollmentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrollRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *EnrollRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentId  string                 `protobuf:"bytes,1,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrollmentRequest) Reset() {
	*x = GetEnrollmentRequest{}
	mi := &file_proto_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrollmentRequest) ProtoMessage() {}

func (x *GetEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *GetEnrollmentRequest) GetEnrollmentId() string {
	if x != nil {
		return x.EnrollmentId
	}
	return ""
}

type ListEnrollmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentsRequest) Reset() {
	*x = ListEnrollmentsRequest{}
	mi := &file_proto_enrollment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentsRequest) ProtoMessage() {}

func (x *ListEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enrollment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*ListEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_enrollment_proto_rawDescGZIP(), []int{2}
}

func (x *ListEnrollmentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListEnrollmentsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListEnrollmentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEnrollmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEnrollmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollments   []*EnrollmentResponse  `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentsResponse) Reset() {
	*x = ListEnrollmentsResponse{}
	mi := &file_proto_enrollment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentsResponse) ProtoMessage() {}

func (x *ListEnrollmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enrollment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentsResponse.ProtoReflect.Descriptor instead.
func (*ListEnrollmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_enrollment_proto_rawDescGZIP(), []int{3}
}

func (x *ListEnrollmentsResponse) GetEnrollments() []*EnrollmentResponse {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

func (x *ListEnrollmentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateProgressRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentId    string                 `protobuf:"bytes,1,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	LessonId        string                 `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	PercentComplete int32                  `protobuf:"varint,3,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_proto_enrollment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enrollment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_enrollment_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProgressRequest) GetEnrollmentId() string {
	if x != nil {
		return x.EnrollmentId
	}
	return ""
}

func (x *UpdateProgressRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *UpdateProgressRequest) GetPercentComplete() int32 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentId  string                 `protobuf:"bytes,1,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_proto_enrollment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enrollment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_enrollment_proto_rawDescGZIP(), []int{5}
}

func (x *GetProgressRequest) GetEnrollmentId() string {
	if x != nil {
		return x.EnrollmentId
	}
	return ""
}

type EnrollmentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentId    string                 `protobuf:"bytes,1,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId        string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	OverallProgress int32                  `protobuf:"varint,5,opt,name=overall_progress,json=overallProgress,proto3" json:"overall_progress,omitempty"`
	EnrolledAt      int64                  `protobuf:"varint,6,opt,name=enrolled_at,json=enrolledAt,proto3" json:"enrolled_at,omitempty"`
	CompletedAt     int64                  `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_proto_enrollment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enrollment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_enrollment_proto_rawDescGZIP(), []int{6}
}

func (x *EnrollmentResponse) GetEnrollmentId() string {
	if x != nil {
		return x.EnrollmentId
	}
	return ""
}

func (x *EnrollmentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrollmentResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *EnrollmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EnrollmentResponse) GetOverallProgress() int32 {
	if x != nil {
		return x.OverallProgress
	}
	return 0
}

func (x *EnrollmentResponse) GetEnrolledAt() int64 {
	if x != nil {
		return x.EnrolledAt
	}
	return 0
}

func (x *EnrollmentResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type ProgressResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentId    string                 `protobuf:"bytes,1,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	OverallProgress int32                  `protobuf:"varint,2,opt,name=overall_progress,json=overallProgress,proto3" json:"overall_progress,omitempty"`
	Lessons         []*LessonProgress      `protobuf:"bytes,3,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_proto_enrollment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enrollment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_enrollment_proto_rawDescGZIP(), []int{7}
}

func (x *ProgressResponse) GetEnrollmentId() string {
	if x != nil {
		return x.EnrollmentId
	}
	return ""
}

func (x *ProgressResponse) GetOverallProgress() int32 {
	if x != nil {
		return x.OverallProgress
	}
	return 0
}

func (x *ProgressResponse) GetLessons() []*LessonProgress {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type LessonProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LessonId        string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	PercentComplete int32                  `protobuf:"varint,2,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"`
	LastAccessed    int64                  `protobuf:"varint,3,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LessonProgress) Reset() {
	*x = LessonProgress{}
	mi := &file_proto_enrollment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonProgress) ProtoMessage() {}

func (x *LessonProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enrollment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonProgress.ProtoReflect.Descriptor instead.
func (*LessonProgress) Descriptor() ([]byte, []int) {
	return file_proto_enrollment_proto_rawDescGZIP(), []int{8}
}

func (x *LessonProgress) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *LessonProgress) GetPercentComplete() int32 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

func (x *LessonProgress) GetLastAccessed() int64 {
	if x != nil {
		return x.LastAccessed
	}
	return 0
}

var File_proto_enrollment_proto protoreflect.FileDescriptor

const file_proto_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x16proto/enrollment.proto\x12\x16learnhub.enrollment.v1\"b\n" +
	"\rEnrollRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\";\n" +
	"\x14GetEnrollmentRequest\x12#\n" +
	"\renrollment_id\x18\x01 \x01(\tR\fenrollmentId\"\x7f\n" +
	"\x16ListEnrollmentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"}\n" +
	"\x17ListEnrollmentsResponse\x12L\n" +
	"\venrollments\x18\x01 \x03(\v2*.learnhub.enrollment.v1.EnrollmentResponseR\venrollments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x84\x01\n" +
	"\x15UpdateProgressRequest\x12#\n" +
	"\renrollment_id\x18\x01 \x01(\tR\fenrollmentId\x12\x1b\n" +
	"\tlesson_id\x18\x02 \x01(\tR\blessonId\x12)\n" +
	"\x10percent_complete\x18\x03 \x01(\x05R\x0fpercentComplete\"9\n" +
	"\x12GetProgressRequest\x12#\n" +
	"\renrollment_id\x18\x01 \x01(\tR\fenrollmentId\"\xf6\x01\n" +
	"\x12EnrollmentResponse\x12#\n" +
	"\renrollment_id\x18\x01 \x01(\tR\fenrollmentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12)\n" +
	"\x10overall_progress\x18\x05 \x01(\x05R\x0foverallProgress\x12\x1f\n" +
	"\venrolled_at\x18\x06 \x01(\x03R\n" +
	"enrolledAt\x12!\n" +
	"\fcompleted_at\x18\a \x01(\x03R\vcompletedAt\"\xa4\x01\n" +
	"\x10ProgressResponse\x12#\n" +
	"\renrollment_id\x18\x01 \x01(\tR\fenrollmentId\x12)\n" +
	"\x10overall_progress\x18\x02 \x01(\x05R\x0foverallProgress\x12@\n" +
	"\alessons\x18\x03 \x03(\v2&.learnhub.enrollment.v1.LessonProgressR\alessons\"}\n" +
	"\x0eLessonProgress\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\x12)\n" +
	"\x10percent_complete\x18\x02 \x01(\x05R\x0fpercentComplete\x12#\n" +
	"\rlast_accessed\x18\x03 \x01(\x03R\flastAccessed2\x9f\x04\n" +
	"\x11EnrollmentService\x12[\n" +
	"\x06Enroll\x12%.learnhub.enrollment.v1.EnrollRequest\x1a*.learnhub.enrollment.v1.EnrollmentResponse\x12i\n" +
	"\rGetEnrollment\x12,.learnhub.enrollment.v1.GetEnrollmentRequest\x1a*.learnhub.enrollment.v1.EnrollmentResponse\x12r\n" +
	"\x0fListEnrollments\x12..learnhub.enrollment.v1.ListEnrollmentsRequest\x1a/.learnhub.enrollment.v1.ListEnrollmentsResponse\x12i\n" +
	"\x0eUpdateProgress\x12-.learnhub.enrollment.v1.UpdateProgressRequest\x1a(.learnhub.enrollment.v1.ProgressResponse\x12c\n" +
	"\vGetProgress\x12*.learnhub.enrollment.v1.GetProgressRequest\x1a(.learnhub.enrollment.v1.ProgressResponseB6Z4github.com/amnayem/skillforge/shared/pb/enrollmentpbb\x06proto3"

var (
	file_proto_enrollment_proto_rawDescOnce sync.Once
	file_proto_enrollment_proto_rawDescData []byte
)

func file_proto_enrollment_proto_rawDescGZIP() []byte {
	file_proto_enrollment_proto_rawDescOnce.Do(func() {
		file_proto_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_enrollment_proto_rawDesc), len(file_proto_enrollment_proto_rawDesc)))
	})
	return file_proto_enrollment_proto_rawDescData
}

var file_proto_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_enrollment_proto_goTypes = []any{
	(*EnrollRequest)(nil),           // 0: learnhub.enrollment.v1.EnrollRequest
	(*GetEnrollmentRequest)(nil),    // 1: learnhub.enrollment.v1.GetEnrollmentRequest
	(*ListEnrollmentsRequest)(nil),  // 2: learnhub.enrollment.v1.ListEnrollmentsRequest
	(*ListEnrollmentsResponse)(nil), // 3: learnhub.enrollment.v1.ListEnrollmentsResponse
	(*UpdateProgressRequest)(nil),   // 4: learnhub.enrollment.v1.UpdateProgressRequest
	(*GetProgressRequest)(nil),      // 5: learnhub.enrollment.v1.GetProgressRequest
	(*EnrollmentResponse)(nil),      // 6: learnhub.enrollment.v1.EnrollmentResponse
	(*ProgressResponse)(nil),        // 7: learnhub.enrollment.v1.ProgressResponse
	(*LessonProgress)(nil),          // 8: learnhub.enrollment.v1.LessonProgress
}
var file_proto_enrollment_proto_depIdxs = []int32{
	6, // 0: learnhub.enrollment.v1.ListEnrollmentsResponse.enrollments:type_name -> learnhub.enrollment.v1.EnrollmentResponse
	8, // 1: learnhub.enrollment.v1.ProgressResponse.lessons:type_name -> learnhub.enrollment.v1.LessonProgress
	0, // 2: learnhub.enrollment.v1.EnrollmentService.Enroll:input_type -> learnhub.enrollment.v1.EnrollRequest
	1, // 3: learnhub.enrollment.v1.EnrollmentService.GetEnrollment:input_type -> learnhub.enrollment.v1.GetEnrollmentRequest
	2, // 4: learnhub.enrollment.v1.EnrollmentService.ListEnrollments:input_type -> learnhub.enrollment.v1.ListEnrollmentsRequest
	4, // 5: learnhub.enrollment.v1.EnrollmentService.UpdateProgress:input_type -> learnhub.enrollment.v1.UpdateProgressRequest
	5, // 6: learnhub.enrollment.v1.EnrollmentService.GetProgress:input_type -> learnhub.enrollment.v1.GetProgressRequest
	6, // 7: learnhub.enrollment.v1.EnrollmentService.Enroll:output_type -> learnhub.enrollment.v1.EnrollmentResponse
	6, // 8: learnhub.enrollment.v1.EnrollmentService.GetEnrollment:output_type -> learnhub.enrollment.v1.EnrollmentResponse
	3, // 9: learnhub.enrollment.v1.EnrollmentService.ListEnrollments:output_type -> learnhub.enrollment.v1.ListEnrollmentsResponse
	7, // 10: learnhub.enrollment.v1.EnrollmentService.UpdateProgress:output_type -> learnhub.enrollment.v1.ProgressResponse
	7, // 11: learnhub.enrollment.v1.EnrollmentService.GetProgress:output_type -> learnhub.enrollment.v1.ProgressResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_enrollment_proto_init() }
func file_proto_enrollment_proto_init() {
	if File_proto_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enrollment_proto_rawDesc), len(file_proto_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_enrollment_proto_goTypes,
		DependencyIndexes: file_proto_enrollment_proto_depIdxs,
		MessageInfos:      file_proto_enrollment_proto_msgTypes,
	}.Build()
	File_proto_enrollment_proto = out.File
	file_proto_enrollment_proto_goTypes = nil
	file_proto_enrollment_proto_depIdxs = nil
}
