// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/analytics.proto

package analyticspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetCourseAnalytics_FullMethodName = "/analytics.v1.AnalyticsService/GetCourseAnalytics"
	AnalyticsService_GetUserAnalytics_FullMethodName   = "/analytics.v1.AnalyticsService/GetUserAnalytics"
	AnalyticsService_GetTenantDashboard_FullMethodName = "/analytics.v1.AnalyticsService/GetTenantDashboard"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetCourseAnalytics(ctx context.Context, in *CourseAnalyticsRequest, opts ...grpc.CallOption) (*CourseAnalyticsResponse, error)
	GetUserAnalytics(ctx context.Context, in *UserAnalyticsRequest, opts ...grpc.CallOption) (*UserAnalyticsResponse, error)
	GetTenantDashboard(ctx context.Context, in *TenantDashboardRequest, opts ...grpc.CallOption) (*TenantDashboardResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetCourseAnalytics(ctx context.Context, in *CourseAnalyticsRequest, opts ...grpc.CallOption) (*CourseAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetCourseAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetUserAnalytics(ctx context.Context, in *UserAnalyticsRequest, opts ...grpc.CallOption) (*UserAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetUserAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTenantDashboard(ctx context.Context, in *TenantDashboardRequest, opts ...grpc.CallOption) (*TenantDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantDashboardResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTenantDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetCourseAnalytics(context.Context, *CourseAnalyticsRequest) (*CourseAnalyticsResponse, error)
	GetUserAnalytics(context.Context, *UserAnalyticsRequest) (*UserAnalyticsResponse, error)
	GetTenantDashboard(context.Context, *TenantDashboardRequest) (*TenantDashboardResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetCourseAnalytics(context.Context, *CourseAnalyticsRequest) (*CourseAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourseAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetUserAnalytics(context.Context, *UserAnalyticsRequest) (*UserAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTenantDashboard(context.Context, *TenantDashboardRequest) (*TenantDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantDashboard not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetCourseAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetCourseAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetCourseAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetCourseAnalytics(ctx, req.(*CourseAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetUserAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetUserAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetUserAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetUserAnalytics(ctx, req.(*UserAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTenantDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTenantDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTenantDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTenantDashboard(ctx, req.(*TenantDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCourseAnalytics",
			Handler:    _AnalyticsService_GetCourseAnalytics_Handler,
		},
		{
			MethodName: "GetUserAnalytics",
			Handler:    _AnalyticsService_GetUserAnalytics_Handler,
		},
		{
			MethodName: "GetTenantDashboard",
			Handler:    _AnalyticsService_GetTenantDashboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytics.proto",
}
