// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/analytics.proto

package analyticspb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseAnalyticsRequest) Reset() {
	*x = CourseAnalyticsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseAnalyticsRequest) ProtoMessage() {}

func (x *CourseAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*CourseAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *CourseAnalyticsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CourseAnalyticsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalEnrollments int32                  `protobuf:"varint,1,opt,name=total_enrollments,json=totalEnrollments,proto3" json:"total_enrollments,omitempty"`
	ActiveStudents   int32                  `protobuf:"varint,2,opt,name=active_students,json=activeStudents,proto3" json:"active_students,omitempty"`
	Completions      int32                  `protobuf:"varint,3,opt,name=completions,proto3" json:"completions,omitempty"`
	AverageProgress  float64                `protobuf:"fixed64,4,opt,name=average_progress,json=averageProgress,proto3" json:"average_progress,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CourseAnalyticsResponse) Reset() {
	*x = CourseAnalyticsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseAnalyticsResponse) ProtoMessage() {}

func (x *CourseAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*CourseAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *CourseAnalyticsResponse) GetTotalEnrollments() int32 {
	if x != nil {
		return x.TotalEnrollments
	}
	return 0
}

func (x *CourseAnalyticsResponse) GetActiveStudents() int32 {
	if x != nil {
		return x.ActiveStudents
	}
	return 0
}

func (x *CourseAnalyticsResponse) GetCompletions() int32 {
	if x != nil {
		return x.Completions
	}
	return 0
}

func (x *CourseAnalyticsResponse) GetAverageProgress() float64 {
	if x != nil {
		return x.AverageProgress
	}
	return 0
}

type UserAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAnalyticsRequest) Reset() {
	*x = UserAnalyticsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnalyticsRequest) ProtoMessage() {}

func (x *UserAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*UserAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *UserAnalyticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserAnalyticsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CoursesEnrolled    int32                  `protobuf:"varint,1,opt,name=courses_enrolled,json=coursesEnrolled,proto3" json:"courses_enrolled,omitempty"`
	CoursesCompleted   int32                  `protobuf:"varint,2,opt,name=courses_completed,json=coursesCompleted,proto3" json:"courses_completed,omitempty"`
	LearningStreakDays int32                  `protobuf:"varint,3,opt,name=learning_streak_days,json=learningStreakDays,proto3" json:"learning_streak_days,omitempty"`
	TotalLearningHours int32                  `protobuf:"varint,4,opt,name=total_learning_hours,json=totalLearningHours,proto3" json:"total_learning_hours,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserAnalyticsResponse) Reset() {
	*x = UserAnalyticsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnalyticsResponse) ProtoMessage() {}

func (x *UserAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*UserAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *UserAnalyticsResponse) GetCoursesEnrolled() int32 {
	if x != nil {
		return x.CoursesEnrolled
	}
	return 0
}

func (x *UserAnalyticsResponse) GetCoursesCompleted() int32 {
	if x != nil {
		return x.CoursesCompleted
	}
	return 0
}

func (x *UserAnalyticsResponse) GetLearningStreakDays() int32 {
	if x != nil {
		return x.LearningStreakDays
	}
	return 0
}

func (x *UserAnalyticsResponse) GetTotalLearningHours() int32 {
	if x != nil {
		return x.TotalLearningHours
	}
	return 0
}

type TenantDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDashboardRequest) Reset() {
	*x = TenantDashboardRequest{}
	mi := &file_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDashboardRequest) ProtoMessage() {}

func (x *TenantDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDashboardRequest.ProtoReflect.Descriptor instead.
func (*TenantDashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TenantDashboardRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type TenantDashboardResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers             int32                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	TotalCourses           int32                  `protobuf:"varint,2,opt,name=total_courses,json=totalCourses,proto3" json:"total_courses,omitempty"`
	TotalEnrollments       int32                  `protobuf:"varint,3,opt,name=total_enrollments,json=totalEnrollments,proto3" json:"total_enrollments,omitempty"`
	ActiveUsersLast_30Days int32                  `protobuf:"varint,4,opt,name=active_users_last_30_days,json=activeUsersLast30Days,proto3" json:"active_users_last_30_days,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TenantDashboardResponse) Reset() {
	*x = TenantDashboardResponse{}
	mi := &file_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDashboardResponse) ProtoMessage() {}

func (x *TenantDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDashboardResponse.ProtoReflect.Descriptor instead.
func (*TenantDashboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *TenantDashboardResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *TenantDashboardResponse) GetTotalCourses() int32 {
	if x != nil {
		return x.TotalCourses
	}
	return 0
}

func (x *TenantDashboardResponse) GetTotalEnrollments() int32 {
	if x != nil {
		return x.TotalEnrollments
	}
	return 0
}

func (x *TenantDashboardResponse) GetActiveUsersLast_30Days() int32 {
	if x != nil {
		return x.ActiveUsersLast_30Days
	}
	return 0
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\fanalytics.v1\x1a\x1cgoogle/api/annotations.proto\"5\n" +
	"\x16CourseAnalyticsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"\xbc\x01\n" +
	"\x17CourseAnalyticsResponse\x12+\n" +
	"\x11total_enrollments\x18\x01 \x01(\x05R\x10totalEnrollments\x12'\n" +
	"\x0factive_students\x18\x02 \x01(\x05R\x0eactiveStudents\x12 \n" +
	"\vcompletions\x18\x03 \x01(\x05R\vcompletions\x12)\n" +
	"\x10average_progress\x18\x04 \x01(\x01R\x0faverageProgress\"/\n" +
	"\x14UserAnalyticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xd3\x01\n" +
	"\x15UserAnalyticsResponse\x12)\n" +
	"\x10courses_enrolled\x18\x01 \x01(\x05R\x0fcoursesEnrolled\x12+\n" +
	"\x11courses_completed\x18\x02 \x01(\x05R\x10coursesCompleted\x120\n" +
	"\x14learning_streak_days\x18\x03 \x01(\x05R\x12learningStreakDays\x120\n" +
	"\x14total_learning_hours\x18\x04 \x01(\x05R\x12totalLearningHours\"5\n" +
	"\x16TenantDashboardRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xc6\x01\n" +
	"\x17TenantDashboardResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x05R\n" +
	"totalUsers\x12#\n" +
	"\rtotal_courses\x18\x02 \x01(\x05R\ftotalCourses\x12+\n" +
	"\x11total_enrollments\x18\x03 \x01(\x05R\x10totalEnrollments\x128\n" +
	"\x19active_users_last_30_days\x18\x04 \x01(\x05R\x15activeUsersLast30Days2\xc0\x03\n" +
	"\x10AnalyticsService\x12\x90\x01\n" +
	"\x12GetCourseAnalytics\x12$.analytics.v1.CourseAnalyticsRequest\x1a%.analytics.v1.CourseAnalyticsResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/analytics/courses/{course_id}\x12\x86\x01\n" +
	"\x10GetUserAnalytics\x12\".analytics.v1.UserAnalyticsRequest\x1a#.analytics.v1.UserAnalyticsResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/analytics/users/{user_id}\x12\x8f\x01\n" +
	"\x12GetTenantDashboard\x12$.analytics.v1.TenantDashboardRequest\x1a%.analytics.v1.TenantDashboardResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/analytics/tenant/{tenant_id}B?Z=github.com/amnayem/skillforge/shared/pb/analytics;analyticspbb\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_analytics_proto_goTypes = []any{
	(*CourseAnalyticsRequest)(nil),  // 0: analytics.v1.CourseAnalyticsRequest
	(*CourseAnalyticsResponse)(nil), // 1: analytics.v1.CourseAnalyticsResponse
	(*UserAnalyticsRequest)(nil),    // 2: analytics.v1.UserAnalyticsRequest
	(*UserAnalyticsResponse)(nil),   // 3: analytics.v1.UserAnalyticsResponse
	(*TenantDashboardRequest)(nil),  // 4: analytics.v1.TenantDashboardRequest
	(*TenantDashboardResponse)(nil), // 5: analytics.v1.TenantDashboardResponse
}
var file_proto_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.v1.AnalyticsService.GetCourseAnalytics:input_type -> analytics.v1.CourseAnalyticsRequest
	2, // 1: analytics.v1.AnalyticsService.GetUserAnalytics:input_type -> analytics.v1.UserAnalyticsRequest
	4, // 2: analytics.v1.AnalyticsService.GetTenantDashboard:input_type -> analytics.v1.TenantDashboardRequest
	1, // 3: analytics.v1.AnalyticsService.GetCourseAnalytics:output_type -> analytics.v1.CourseAnalyticsResponse
	3, // 4: analytics.v1.AnalyticsService.GetUserAnalytics:output_type -> analytics.v1.UserAnalyticsResponse
	5, // 5: analytics.v1.AnalyticsService.GetTenantDashboard:output_type -> analytics.v1.TenantDashboardResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
