// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ai.proto

package aipb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompletedCourseIds []string               `protobuf:"bytes,3,rep,name=completed_course_ids,json=completedCourseIds,proto3" json:"completed_course_ids,omitempty"`
	SkillsOfInterest   []string               `protobuf:"bytes,4,rep,name=skills_of_interest,json=skillsOfInterest,proto3" json:"skills_of_interest,omitempty"`
	Limit              int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecommendationRequest) Reset() {
	*x = RecommendationRequest{}
	mi := &file_proto_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRequest) ProtoMessage() {}

func (x *RecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRequest.ProtoReflect.Descriptor instead.
func (*RecommendationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RecommendationRequest) GetCompletedCourseIds() []string {
	if x != nil {
		return x.CompletedCourseIds
	}
	return nil
}

func (x *RecommendationRequest) GetSkillsOfInterest() []string {
	if x != nil {
		return x.SkillsOfInterest
	}
	return nil
}

func (x *RecommendationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecommendedCourse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourseId        string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MatchReason     string                 `protobuf:"bytes,3,opt,name=match_reason,json=matchReason,proto3" json:"match_reason,omitempty"`
	ConfidenceScore float64                `protobuf:"fixed64,4,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendedCourse) Reset() {
	*x = RecommendedCourse{}
	mi := &file_proto_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedCourse) ProtoMessage() {}

func (x *RecommendedCourse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedCourse.ProtoReflect.Descriptor instead.
func (*RecommendedCourse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendedCourse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *RecommendedCourse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecommendedCourse) GetMatchReason() string {
	if x != nil {
		return x.MatchReason
	}
	return ""
}

func (x *RecommendedCourse) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

type RecommendationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*RecommendedCourse   `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendationResponse) Reset() {
	*x = RecommendationResponse{}
	mi := &file_proto_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationResponse) ProtoMessage() {}

func (x *RecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationResponse.ProtoReflect.Descriptor instead.
func (*RecommendationResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendationResponse) GetRecommendations() []*RecommendedCourse {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type TagContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentText   string                 `protobuf:"bytes,1,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	ContentTitle  string                 `protobuf:"bytes,2,opt,name=content_title,json=contentTitle,proto3" json:"content_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagContentRequest) Reset() {
	*x = TagContentRequest{}
	mi := &file_proto_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagContentRequest) ProtoMessage() {}

func (x *TagContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagContentRequest.ProtoReflect.Descriptor instead.
func (*TagContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{3}
}

func (x *TagContentRequest) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *TagContentRequest) GetContentTitle() string {
	if x != nil {
		return x.ContentTitle
	}
	return ""
}

type TagContentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Categories      []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	DifficultyLevel string                 `protobuf:"bytes,2,opt,name=difficulty_level,json=difficultyLevel,proto3" json:"difficulty_level,omitempty"`
	Keywords        []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TagContentResponse) Reset() {
	*x = TagContentResponse{}
	mi := &file_proto_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagContentResponse) ProtoMessage() {}

func (x *TagContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagContentResponse.ProtoReflect.Descriptor instead.
func (*TagContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{4}
}

func (x *TagContentResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *TagContentResponse) GetDifficultyLevel() string {
	if x != nil {
		return x.DifficultyLevel
	}
	return ""
}

func (x *TagContentResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type SummarizeCourseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourseTitle     string                 `protobuf:"bytes,1,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	LessonTitles    []string               `protobuf:"bytes,2,rep,name=lesson_titles,json=lessonTitles,proto3" json:"lesson_titles,omitempty"`
	InstructorNotes string                 `protobuf:"bytes,3,opt,name=instructor_notes,json=instructorNotes,proto3" json:"instructor_notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SummarizeCourseRequest) Reset() {
	*x = SummarizeCourseRequest{}
	mi := &file_proto_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeCourseRequest) ProtoMessage() {}

func (x *SummarizeCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeCourseRequest.ProtoReflect.Descriptor instead.
func (*SummarizeCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{5}
}

func (x *SummarizeCourseRequest) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *SummarizeCourseRequest) GetLessonTitles() []string {
	if x != nil {
		return x.LessonTitles
	}
	return nil
}

func (x *SummarizeCourseRequest) GetInstructorNotes() string {
	if x != nil {
		return x.InstructorNotes
	}
	return ""
}

type SummarizeCourseResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Summary            string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	LearningObjectives string                 `protobuf:"bytes,2,opt,name=learning_objectives,json=learningObjectives,proto3" json:"learning_objectives,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SummarizeCourseResponse) Reset() {
	*x = SummarizeCourseResponse{}
	mi := &file_proto_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeCourseResponse) ProtoMessage() {}

func (x *SummarizeCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeCourseResponse.ProtoReflect.Descriptor instead.
func (*SummarizeCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{6}
}

func (x *SummarizeCourseResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummarizeCourseResponse) GetLearningObjectives() string {
	if x != nil {
		return x.LearningObjectives
	}
	return ""
}

var File_proto_ai_proto protoreflect.FileDescriptor

const file_proto_ai_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ai.proto\x12\x05ai.v1\x1a\x1cgoogle/api/annotations.proto\"\xc3\x01\n" +
	"\x15RecommendationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x120\n" +
	"\x14completed_course_ids\x18\x03 \x03(\tR\x12completedCourseIds\x12,\n" +
	"\x12skills_of_interest\x18\x04 \x03(\tR\x10skillsOfInterest\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x94\x01\n" +
	"\x11RecommendedCourse\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fmatch_reason\x18\x03 \x01(\tR\vmatchReason\x12)\n" +
	"\x10confidence_score\x18\x04 \x01(\x01R\x0fconfidenceScore\"\\\n" +
	"\x16RecommendationResponse\x12B\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x18.ai.v1.RecommendedCourseR\x0frecommendations\"[\n" +
	"\x11TagContentRequest\x12!\n" +
	"\fcontent_text\x18\x01 \x01(\tR\vcontentText\x12#\n" +
	"\rcontent_title\x18\x02 \x01(\tR\fcontentTitle\"{\n" +
	"\x12TagContentResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\x12)\n" +
	"\x10difficulty_level\x18\x02 \x01(\tR\x0fdifficultyLevel\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\"\x8b\x01\n" +
	"\x16SummarizeCourseRequest\x12!\n" +
	"\fcourse_title\x18\x01 \x01(\tR\vcourseTitle\x12#\n" +
	"\rlesson_titles\x18\x02 \x03(\tR\flessonTitles\x12)\n" +
	"\x10instructor_notes\x18\x03 \x01(\tR\x0finstructorNotes\"d\n" +
	"\x17SummarizeCourseResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12/\n" +
	"\x13learning_objectives\x18\x02 \x01(\tR\x12learningObjectives2\xe4\x02\n" +
	"\tAIService\x12v\n" +
	"\x10RecommendCourses\x12\x1c.ai.v1.RecommendationRequest\x1a\x1d.ai.v1.RecommendationResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/ai/recommendations\x12d\n" +
	"\n" +
	"TagContent\x12\x18.ai.v1.TagContentRequest\x1a\x19.ai.v1.TagContentResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/ai/content/tag\x12y\n" +
	"\x0fSummarizeCourse\x12\x1d.ai.v1.SummarizeCourseRequest\x1a\x1e.ai.v1.SummarizeCourseResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/ai/content/summarizeB1Z/github.com/amnayem/skillforge/shared/pb/ai;aipbb\x06proto3"

var (
	file_proto_ai_proto_rawDescOnce sync.Once
	file_proto_ai_proto_rawDescData []byte
)

func file_proto_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)))
	})
	return file_proto_ai_proto_rawDescData
}

var file_proto_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_ai_proto_goTypes = []any{
	(*RecommendationRequest)(nil),   // 0: ai.v1.RecommendationRequest
	(*RecommendedCourse)(nil),       // 1: ai.v1.RecommendedCourse
	(*RecommendationResponse)(nil),  // 2: ai.v1.RecommendationResponse
	(*TagContentRequest)(nil),       // 3: ai.v1.TagContentRequest
	(*TagContentResponse)(nil),      // 4: ai.v1.TagContentResponse
	(*SummarizeCourseRequest)(nil),  // 5: ai.v1.SummarizeCourseRequest
	(*SummarizeCourseResponse)(nil), // 6: ai.v1.SummarizeCourseResponse
}
var file_proto_ai_proto_depIdxs = []int32{
	1, // 0: ai.v1.RecommendationResponse.recommendations:type_name -> ai.v1.RecommendedCourse
	0, // 1: ai.v1.AIService.RecommendCourses:input_type -> ai.v1.RecommendationRequest
	3, // 2: ai.v1.AIService.TagContent:input_type -> ai.v1.TagContentRequest
	5, // 3: ai.v1.AIService.SummarizeCourse:input_type -> ai.v1.SummarizeCourseRequest
	2, // 4: ai.v1.AIService.RecommendCourses:output_type -> ai.v1.RecommendationResponse
	4, // 5: ai.v1.AIService.TagContent:output_type -> ai.v1.TagContentResponse
	6, // 6: ai.v1.AIService.SummarizeCourse:output_type -> ai.v1.SummarizeCourseResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ai_proto_init() }
func file_proto_ai_proto_init() {
	if File_proto_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_proto = out.File
	file_proto_ai_proto_goTypes = nil
	file_proto_ai_proto_depIdxs = nil
}
