// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/ai.proto

package aipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AIService_RecommendCourses_FullMethodName = "/ai.v1.AIService/RecommendCourses"
	AIService_TagContent_FullMethodName       = "/ai.v1.AIService/TagContent"
	AIService_SummarizeCourse_FullMethodName  = "/ai.v1.AIService/SummarizeCourse"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	RecommendCourses(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
	TagContent(ctx context.Context, in *TagContentRequest, opts ...grpc.CallOption) (*TagContentResponse, error)
	SummarizeCourse(ctx context.Context, in *SummarizeCourseRequest, opts ...grpc.CallOption) (*SummarizeCourseResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) RecommendCourses(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, AIService_RecommendCourses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) TagContent(ctx context.Context, in *TagContentRequest, opts ...grpc.CallOption) (*TagContentResponse, error) {
	out := new(TagContentResponse)
	err := c.cc.Invoke(ctx, AIService_TagContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) SummarizeCourse(ctx context.Context, in *SummarizeCourseRequest, opts ...grpc.CallOption) (*SummarizeCourseResponse, error) {
	out := new(SummarizeCourseResponse)
	err := c.cc.Invoke(ctx, AIService_SummarizeCourse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility
type AIServiceServer interface {
	RecommendCourses(context.Context, *RecommendationRequest) (*RecommendationResponse, error)
	TagContent(context.Context, *TagContentRequest) (*TagContentResponse, error)
	SummarizeCourse(context.Context, *SummarizeCourseRequest) (*SummarizeCourseResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIServiceServer struct {
}

func (UnimplementedAIServiceServer) RecommendCourses(context.Context, *RecommendationRequest) (*RecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendCourses not implemented")
}
func (UnimplementedAIServiceServer) TagContent(context.Context, *TagContentRequest) (*TagContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagContent not implemented")
}
func (UnimplementedAIServiceServer) SummarizeCourse(context.Context, *SummarizeCourseRequest) (*SummarizeCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SummarizeCourse not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_RecommendCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).RecommendCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_RecommendCourses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).RecommendCourses(ctx, req.(*RecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_TagContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).TagContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_TagContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).TagContent(ctx, req.(*TagContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_SummarizeCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).SummarizeCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_SummarizeCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).SummarizeCourse(ctx, req.(*SummarizeCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecommendCourses",
			Handler:    _AIService_RecommendCourses_Handler,
		},
		{
			MethodName: "TagContent",
			Handler:    _AIService_TagContent_Handler,
		},
		{
			MethodName: "SummarizeCourse",
			Handler:    _AIService_SummarizeCourse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai.proto",
}
