// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/certification.proto

package certificationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CertificationService_CreateTemplate_FullMethodName      = "/certification.v1.CertificationService/CreateTemplate"
	CertificationService_GetUserCertificates_FullMethodName = "/certification.v1.CertificationService/GetUserCertificates"
	CertificationService_VerifyCertificate_FullMethodName   = "/certification.v1.CertificationService/VerifyCertificate"
)

// CertificationServiceClient is the client API for CertificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CertificationServiceClient interface {
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CertificateTemplate, error)
	GetUserCertificates(ctx context.Context, in *GetUserCertificatesRequest, opts ...grpc.CallOption) (*GetUserCertificatesResponse, error)
	VerifyCertificate(ctx context.Context, in *VerifyCertificateRequest, opts ...grpc.CallOption) (*VerifyCertificateResponse, error)
}

type certificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificationServiceClient(cc grpc.ClientConnInterface) CertificationServiceClient {
	return &certificationServiceClient{cc}
}

func (c *certificationServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CertificateTemplate, error) {
	out := new(CertificateTemplate)
	err := c.cc.Invoke(ctx, CertificationService_CreateTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificationServiceClient) GetUserCertificates(ctx context.Context, in *GetUserCertificatesRequest, opts ...grpc.CallOption) (*GetUserCertificatesResponse, error) {
	out := new(GetUserCertificatesResponse)
	err := c.cc.Invoke(ctx, CertificationService_GetUserCertificates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificationServiceClient) VerifyCertificate(ctx context.Context, in *VerifyCertificateRequest, opts ...grpc.CallOption) (*VerifyCertificateResponse, error) {
	out := new(VerifyCertificateResponse)
	err := c.cc.Invoke(ctx, CertificationService_VerifyCertificate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificationServiceServer is the server API for CertificationService service.
// All implementations must embed UnimplementedCertificationServiceServer
// for forward compatibility
type CertificationServiceServer interface {
	CreateTemplate(context.Context, *CreateTemplateRequest) (*CertificateTemplate, error)
	GetUserCertificates(context.Context, *GetUserCertificatesRequest) (*GetUserCertificatesResponse, error)
	VerifyCertificate(context.Context, *VerifyCertificateRequest) (*VerifyCertificateResponse, error)
	mustEmbedUnimplementedCertificationServiceServer()
}

// UnimplementedCertificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCertificationServiceServer struct {
}

func (UnimplementedCertificationServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*CertificateTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedCertificationServiceServer) GetUserCertificates(context.Context, *GetUserCertificatesRequest) (*GetUserCertificatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCertificates not implemented")
}
func (UnimplementedCertificationServiceServer) VerifyCertificate(context.Context, *VerifyCertificateRequest) (*VerifyCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCertificate not implemented")
}
func (UnimplementedCertificationServiceServer) mustEmbedUnimplementedCertificationServiceServer() {}

// UnsafeCertificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificationServiceServer will
// result in compilation errors.
type UnsafeCertificationServiceServer interface {
	mustEmbedUnimplementedCertificationServiceServer()
}

func RegisterCertificationServiceServer(s grpc.ServiceRegistrar, srv CertificationServiceServer) {
	s.RegisterService(&CertificationService_ServiceDesc, srv)
}

func _CertificationService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificationServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificationService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificationServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificationService_GetUserCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCertificatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificationServiceServer).GetUserCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificationService_GetUserCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificationServiceServer).GetUserCertificates(ctx, req.(*GetUserCertificatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificationService_VerifyCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificationServiceServer).VerifyCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificationService_VerifyCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificationServiceServer).VerifyCertificate(ctx, req.(*VerifyCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificationService_ServiceDesc is the grpc.ServiceDesc for CertificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "certification.v1.CertificationService",
	HandlerType: (*CertificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _CertificationService_CreateTemplate_Handler,
		},
		{
			MethodName: "GetUserCertificates",
			Handler:    _CertificationService_GetUserCertificates_Handler,
		},
		{
			MethodName: "VerifyCertificate",
			Handler:    _CertificationService_VerifyCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/certification.proto",
}
