// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/certification.proto

package certificationpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BackgroundUrl string                 `protobuf:"bytes,4,opt,name=background_url,json=backgroundUrl,proto3" json:"background_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateTemplate) Reset() {
	*x = CertificateTemplate{}
	mi := &file_proto_certification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateTemplate) ProtoMessage() {}

func (x *CertificateTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateTemplate.ProtoReflect.Descriptor instead.
func (*CertificateTemplate) Descriptor() ([]byte, []int) {
	return file_proto_certification_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateTemplate) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CertificateTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CertificateTemplate) GetBackgroundUrl() string {
	if x != nil {
		return x.BackgroundUrl
	}
	return ""
}

func (x *CertificateTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Certificate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId         string                 `protobuf:"bytes,4,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	VerificationCode string                 `protobuf:"bytes,5,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	PdfUrl           string                 `protobuf:"bytes,6,opt,name=pdf_url,json=pdfUrl,proto3" json:"pdf_url,omitempty"`
	IssuedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_proto_certification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_proto_certification_proto_rawDescGZIP(), []int{1}
}

func (x *Certificate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Certificate) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Certificate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Certificate) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Certificate) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *Certificate) GetPdfUrl() string {
	if x != nil {
		return x.PdfUrl
	}
	return ""
}

func (x *Certificate) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BackgroundUrl string                 `protobuf:"bytes,3,opt,name=background_url,json=backgroundUrl,proto3" json:"background_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_proto_certification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_certification_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTemplateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetBackgroundUrl() string {
	if x != nil {
		return x.BackgroundUrl
	}
	return ""
}

type GetUserCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCertificatesRequest) Reset() {
	*x = GetUserCertificatesRequest{}
	mi := &file_proto_certification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCertificatesRequest) ProtoMessage() {}

func (x *GetUserCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCertificatesRequest.ProtoReflect.Descriptor instead.
func (*GetUserCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_certification_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserCertificatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserCertificatesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetUserCertificatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*Certificate         `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCertificatesResponse) Reset() {
	*x = GetUserCertificatesResponse{}
	mi := &file_proto_certification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCertificatesResponse) ProtoMessage() {}

func (x *GetUserCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCertificatesResponse.ProtoReflect.Descriptor instead.
func (*GetUserCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_certification_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserCertificatesResponse) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type VerifyCertificateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VerificationCode string                 `protobuf:"bytes,1,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyCertificateRequest) Reset() {
	*x = VerifyCertificateRequest{}
	mi := &file_proto_certification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCertificateRequest) ProtoMessage() {}

func (x *VerifyCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCertificateRequest.ProtoReflect.Descriptor instead.
func (*VerifyCertificateRequest) Descriptor() ([]byte, []int) {
	return file_proto_certification_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyCertificateRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type VerifyCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Certificate   *Certificate           `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	StudentName   string                 `protobuf:"bytes,3,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	CourseName    string                 `protobuf:"bytes,4,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCertificateResponse) Reset() {
	*x = VerifyCertificateResponse{}
	mi := &file_proto_certification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCertificateResponse) ProtoMessage() {}

func (x *VerifyCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCertificateResponse.ProtoReflect.Descriptor instead.
func (*VerifyCertificateResponse) Descriptor() ([]byte, []int) {
	return file_proto_certification_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyCertificateResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *VerifyCertificateResponse) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *VerifyCertificateResponse) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *VerifyCertificateResponse) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

var File_proto_certification_proto protoreflect.FileDescriptor

const file_proto_certification_proto_rawDesc = "" +
	"\n" +
	"\x19proto/certification.proto\x12\x10certification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xb8\x01\n" +
	"\x13CertificateTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0ebackground_url\x18\x04 \x01(\tR\rbackgroundUrl\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xef\x01\n" +
	"\vCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x04 \x01(\tR\bcourseId\x12+\n" +
	"\x11verification_code\x18\x05 \x01(\tR\x10verificationCode\x12\x17\n" +
	"\apdf_url\x18\x06 \x01(\tR\x06pdfUrl\x127\n" +
	"\tissued_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"o\n" +
	"\x15CreateTemplateRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0ebackground_url\x18\x03 \x01(\tR\rbackgroundUrl\"R\n" +
	"\x1aGetUserCertificatesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"`\n" +
	"\x1bGetUserCertificatesResponse\x12A\n" +
	"\fcertificates\x18\x01 \x03(\v2\x1d.certification.v1.CertificateR\fcertificates\"G\n" +
	"\x18VerifyCertificateRequest\x12+\n" +
	"\x11verification_code\x18\x01 \x01(\tR\x10verificationCode\"\xbb\x01\n" +
	"\x19VerifyCertificateResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12?\n" +
	"\vcertificate\x18\x02 \x01(\v2\x1d.certification.v1.CertificateR\vcertificate\x12!\n" +
	"\fstudent_name\x18\x03 \x01(\tR\vstudentName\x12\x1f\n" +
	"\vcourse_name\x18\x04 \x01(\tR\n" +
	"courseName2\xdf\x03\n" +
	"\x14CertificationService\x12\x8b\x01\n" +
	"\x0eCreateTemplate\x12'.certification.v1.CreateTemplateRequest\x1a%.certification.v1.CertificateTemplate\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/certificates/templates\x12\x90\x01\n" +
	"\x13GetUserCertificates\x12,.certification.v1.GetUserCertificatesRequest\x1a-.certification.v1.GetUserCertificatesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/certificates\x12\xa5\x01\n" +
	"\x11VerifyCertificate\x12*.certification.v1.VerifyCertificateRequest\x1a+.certification.v1.VerifyCertificateResponse\"7\x82\xd3\xe4\x93\x021\x12//api/v1/certificates/{verification_code}/verifyBGZEgithub.com/amnayem/skillforge/shared/pb/certification;certificationpbb\x06proto3"

var (
	file_proto_certification_proto_rawDescOnce sync.Once
	file_proto_certification_proto_rawDescData []byte
)

func file_proto_certification_proto_rawDescGZIP() []byte {
	file_proto_certification_proto_rawDescOnce.Do(func() {
		file_proto_certification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_certification_proto_rawDesc), len(file_proto_certification_proto_rawDesc)))
	})
	return file_proto_certification_proto_rawDescData
}

var file_proto_certification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_certification_proto_goTypes = []any{
	(*CertificateTemplate)(nil),         // 0: certification.v1.CertificateTemplate
	(*Certificate)(nil),                 // 1: certification.v1.Certificate
	(*CreateTemplateRequest)(nil),       // 2: certification.v1.CreateTemplateRequest
	(*GetUserCertificatesRequest)(nil),  // 3: certification.v1.GetUserCertificatesRequest
	(*GetUserCertificatesResponse)(nil), // 4: certification.v1.GetUserCertificatesResponse
	(*VerifyCertificateRequest)(nil),    // 5: certification.v1.VerifyCertificateRequest
	(*VerifyCertificateResponse)(nil),   // 6: certification.v1.VerifyCertificateResponse
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
}
var file_proto_certification_proto_depIdxs = []int32{
	7, // 0: certification.v1.CertificateTemplate.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: certification.v1.Certificate.issued_at:type_name -> google.protobuf.Timestamp
	1, // 2: certification.v1.GetUserCertificatesResponse.certificates:type_name -> certification.v1.Certificate
	1, // 3: certification.v1.VerifyCertificateResponse.certificate:type_name -> certification.v1.Certificate
	2, // 4: certification.v1.CertificationService.CreateTemplate:input_type -> certification.v1.CreateTemplateRequest
	3, // 5: certification.v1.CertificationService.GetUserCertificates:input_type -> certification.v1.GetUserCertificatesRequest
	5, // 6: certification.v1.CertificationService.VerifyCertificate:input_type -> certification.v1.VerifyCertificateRequest
	0, // 7: certification.v1.CertificationService.CreateTemplate:output_type -> certification.v1.CertificateTemplate
	4, // 8: certification.v1.CertificationService.GetUserCertificates:output_type -> certification.v1.GetUserCertificatesResponse
	6, // 9: certification.v1.CertificationService.VerifyCertificate:output_type -> certification.v1.VerifyCertificateResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_certification_proto_init() }
func file_proto_certification_proto_init() {
	if File_proto_certification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_certification_proto_rawDesc), len(file_proto_certification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_certification_proto_goTypes,
		DependencyIndexes: file_proto_certification_proto_depIdxs,
		MessageInfos:      file_proto_certification_proto_msgTypes,
	}.Build()
	File_proto_certification_proto = out.File
	file_proto_certification_proto_goTypes = nil
	file_proto_certification_proto_depIdxs = nil
}
