// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/assessment.proto

package assessmentpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Assessment struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId               string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LessonId               string                 `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Title                  string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PassingScorePercentage int32                  `protobuf:"varint,6,opt,name=passing_score_percentage,json=passingScorePercentage,proto3" json:"passing_score_percentage,omitempty"`
	Questions              []*Question            `protobuf:"bytes,7,rep,name=questions,proto3" json:"questions,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Assessment) Reset() {
	*x = Assessment{}
	mi := &file_proto_assessment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assessment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assessment) ProtoMessage() {}

func (x *Assessment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assessment.ProtoReflect.Descriptor instead.
func (*Assessment) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{0}
}

func (x *Assessment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Assessment) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Assessment) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *Assessment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Assessment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Assessment) GetPassingScorePercentage() int32 {
	if x != nil {
		return x.PassingScorePercentage
	}
	return 0
}

func (x *Assessment) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *Assessment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Assessment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "multiple_choice", "true_false", "short_answer", "essay"
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`                                  // for multiple choice
	CorrectAnswer string                 `protobuf:"bytes,5,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"` // for auto-grading
	Points        int32                  `protobuf:"varint,6,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_assessment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *Question) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type CreateAssessmentRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LessonId               string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Title                  string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PassingScorePercentage int32                  `protobuf:"varint,4,opt,name=passing_score_percentage,json=passingScorePercentage,proto3" json:"passing_score_percentage,omitempty"`
	Questions              []*Question            `protobuf:"bytes,5,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateAssessmentRequest) Reset() {
	*x = CreateAssessmentRequest{}
	mi := &file_proto_assessment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssessmentRequest) ProtoMessage() {}

func (x *CreateAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssessmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAssessmentRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *CreateAssessmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAssessmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAssessmentRequest) GetPassingScorePercentage() int32 {
	if x != nil {
		return x.PassingScorePercentage
	}
	return 0
}

func (x *CreateAssessmentRequest) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GetAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssessmentRequest) Reset() {
	*x = GetAssessmentRequest{}
	mi := &file_proto_assessment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssessmentRequest) ProtoMessage() {}

func (x *GetAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssessmentRequest.ProtoReflect.Descriptor instead.
func (*GetAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssessmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubmitAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	Answers       []*Answer              `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAssessmentRequest) Reset() {
	*x = SubmitAssessmentRequest{}
	mi := &file_proto_assessment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAssessmentRequest) ProtoMessage() {}

func (x *SubmitAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAssessmentRequest.ProtoReflect.Descriptor instead.
func (*SubmitAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAssessmentRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *SubmitAssessmentRequest) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerText    string                 `protobuf:"bytes,2,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_proto_assessment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{5}
}

func (x *Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Answer) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

type SubmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "graded", "pending_review"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionResponse) Reset() {
	*x = SubmissionResponse{}
	mi := &file_proto_assessment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionResponse) ProtoMessage() {}

func (x *SubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionResponse.ProtoReflect.Descriptor instead.
func (*SubmissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{6}
}

func (x *SubmissionResponse) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *SubmissionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	SubmissionId  string                 `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeRequest) Reset() {
	*x = GetGradeRequest{}
	mi := &file_proto_assessment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeRequest) ProtoMessage() {}

func (x *GetGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeRequest.ProtoReflect.Descriptor instead.
func (*GetGradeRequest) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{7}
}

func (x *GetGradeRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *GetGradeRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

type GradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	TotalPoints   int32                  `protobuf:"varint,2,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
	EarnedPoints  int32                  `protobuf:"varint,3,opt,name=earned_points,json=earnedPoints,proto3" json:"earned_points,omitempty"`
	Passed        bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	Feedback      string                 `protobuf:"bytes,5,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeResponse) Reset() {
	*x = GradeResponse{}
	mi := &file_proto_assessment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResponse) ProtoMessage() {}

func (x *GradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assessment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResponse.ProtoReflect.Descriptor instead.
func (*GradeResponse) Descriptor() ([]byte, []int) {
	return file_proto_assessment_proto_rawDescGZIP(), []int{8}
}

func (x *GradeResponse) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *GradeResponse) GetTotalPoints() int32 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

func (x *GradeResponse) GetEarnedPoints() int32 {
	if x != nil {
		return x.EarnedPoints
	}
	return 0
}

func (x *GradeResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *GradeResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

var File_proto_assessment_proto protoreflect.FileDescriptor

const file_proto_assessment_proto_rawDesc = "" +
	"\n" +
	"\x16proto/assessment.proto\x12\rassessment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xf5\x02\n" +
	"\n" +
	"Assessment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tlesson_id\x18\x03 \x01(\tR\blessonId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x128\n" +
	"\x18passing_score_percentage\x18\x06 \x01(\x05R\x16passingScorePercentage\x125\n" +
	"\tquestions\x18\a \x03(\v2\x17.assessment.v1.QuestionR\tquestions\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9b\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12%\n" +
	"\x0ecorrect_answer\x18\x05 \x01(\tR\rcorrectAnswer\x12\x16\n" +
	"\x06points\x18\x06 \x01(\x05R\x06points\"\xdf\x01\n" +
	"\x17CreateAssessmentRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x128\n" +
	"\x18passing_score_percentage\x18\x04 \x01(\x05R\x16passingScorePercentage\x125\n" +
	"\tquestions\x18\x05 \x03(\v2\x17.assessment.v1.QuestionR\tquestions\"&\n" +
	"\x14GetAssessmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\x17SubmitAssessmentRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12/\n" +
	"\aanswers\x18\x02 \x03(\v2\x15.assessment.v1.AnswerR\aanswers\"J\n" +
	"\x06Answer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1f\n" +
	"\vanswer_text\x18\x02 \x01(\tR\n" +
	"answerText\"Q\n" +
	"\x12SubmissionResponse\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"[\n" +
	"\x0fGetGradeRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12#\n" +
	"\rsubmission_id\x18\x02 \x01(\tR\fsubmissionId\"\xb0\x01\n" +
	"\rGradeResponse\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12!\n" +
	"\ftotal_points\x18\x02 \x01(\x05R\vtotalPoints\x12#\n" +
	"\rearned_points\x18\x03 \x01(\x05R\fearnedPoints\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12\x1a\n" +
	"\bfeedback\x18\x05 \x01(\tR\bfeedback2\xb3\x04\n" +
	"\x11AssessmentService\x12u\n" +
	"\x10CreateAssessment\x12&.assessment.v1.CreateAssessmentRequest\x1a\x19.assessment.v1.Assessment\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/assessments\x12q\n" +
	"\rGetAssessment\x12#.assessment.v1.GetAssessmentRequest\x1a\x19.assessment.v1.Assessment\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/assessments/{id}\x12\x99\x01\n" +
	"\x10SubmitAssessment\x12&.assessment.v1.SubmitAssessmentRequest\x1a!.assessment.v1.SubmissionResponse\":\x82\xd3\xe4\x93\x024:\x01*\"//api/v1/assessments/{assessment_id}/submissions\x12\x97\x01\n" +
	"\bGetGrade\x12\x1e.assessment.v1.GetGradeRequest\x1a\x1c.assessment.v1.GradeResponse\"M\x82\xd3\xe4\x93\x02G\x12E/api/v1/assessments/{assessment_id}/submissions/{submission_id}/gradeBAZ?github.com/amnayem/skillforge/shared/pb/assessment;assessmentpbb\x06proto3"

var (
	file_proto_assessment_proto_rawDescOnce sync.Once
	file_proto_assessment_proto_rawDescData []byte
)

func file_proto_assessment_proto_rawDescGZIP() []byte {
	file_proto_assessment_proto_rawDescOnce.Do(func() {
		file_proto_assessment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_assessment_proto_rawDesc), len(file_proto_assessment_proto_rawDesc)))
	})
	return file_proto_assessment_proto_rawDescData
}

var file_proto_assessment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_assessment_proto_goTypes = []any{
	(*Assessment)(nil),              // 0: assessment.v1.Assessment
	(*Question)(nil),                // 1: assessment.v1.Question
	(*CreateAssessmentRequest)(nil), // 2: assessment.v1.CreateAssessmentRequest
	(*GetAssessmentRequest)(nil),    // 3: assessment.v1.GetAssessmentRequest
	(*SubmitAssessmentRequest)(nil), // 4: assessment.v1.SubmitAssessmentRequest
	(*Answer)(nil),                  // 5: assessment.v1.Answer
	(*SubmissionResponse)(nil),      // 6: assessment.v1.SubmissionResponse
	(*GetGradeRequest)(nil),         // 7: assessment.v1.GetGradeRequest
	(*GradeResponse)(nil),           // 8: assessment.v1.GradeResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_proto_assessment_proto_depIdxs = []int32{
	1, // 0: assessment.v1.Assessment.questions:type_name -> assessment.v1.Question
	9, // 1: assessment.v1.Assessment.created_at:type_name -> google.protobuf.Timestamp
	9, // 2: assessment.v1.Assessment.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: assessment.v1.CreateAssessmentRequest.questions:type_name -> assessment.v1.Question
	5, // 4: assessment.v1.SubmitAssessmentRequest.answers:type_name -> assessment.v1.Answer
	2, // 5: assessment.v1.AssessmentService.CreateAssessment:input_type -> assessment.v1.CreateAssessmentRequest
	3, // 6: assessment.v1.AssessmentService.GetAssessment:input_type -> assessment.v1.GetAssessmentRequest
	4, // 7: assessment.v1.AssessmentService.SubmitAssessment:input_type -> assessment.v1.SubmitAssessmentRequest
	7, // 8: assessment.v1.AssessmentService.GetGrade:input_type -> assessment.v1.GetGradeRequest
	0, // 9: assessment.v1.AssessmentService.CreateAssessment:output_type -> assessment.v1.Assessment
	0, // 10: assessment.v1.AssessmentService.GetAssessment:output_type -> assessment.v1.Assessment
	6, // 11: assessment.v1.AssessmentService.SubmitAssessment:output_type -> assessment.v1.SubmissionResponse
	8, // 12: assessment.v1.AssessmentService.GetGrade:output_type -> assessment.v1.GradeResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_assessment_proto_init() }
func file_proto_assessment_proto_init() {
	if File_proto_assessment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_assessment_proto_rawDesc), len(file_proto_assessment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_assessment_proto_goTypes,
		DependencyIndexes: file_proto_assessment_proto_depIdxs,
		MessageInfos:      file_proto_assessment_proto_msgTypes,
	}.Build()
	File_proto_assessment_proto = out.File
	file_proto_assessment_proto_goTypes = nil
	file_proto_assessment_proto_depIdxs = nil
}
