// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/assessment.proto

package assessmentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AssessmentService_CreateAssessment_FullMethodName = "/assessment.v1.AssessmentService/CreateAssessment"
	AssessmentService_GetAssessment_FullMethodName    = "/assessment.v1.AssessmentService/GetAssessment"
	AssessmentService_SubmitAssessment_FullMethodName = "/assessment.v1.AssessmentService/SubmitAssessment"
	AssessmentService_GetGrade_FullMethodName         = "/assessment.v1.AssessmentService/GetGrade"
)

// AssessmentServiceClient is the client API for AssessmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssessmentServiceClient interface {
	CreateAssessment(ctx context.Context, in *CreateAssessmentRequest, opts ...grpc.CallOption) (*Assessment, error)
	GetAssessment(ctx context.Context, in *GetAssessmentRequest, opts ...grpc.CallOption) (*Assessment, error)
	SubmitAssessment(ctx context.Context, in *SubmitAssessmentRequest, opts ...grpc.CallOption) (*SubmissionResponse, error)
	GetGrade(ctx context.Context, in *GetGradeRequest, opts ...grpc.CallOption) (*GradeResponse, error)
}

type assessmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssessmentServiceClient(cc grpc.ClientConnInterface) AssessmentServiceClient {
	return &assessmentServiceClient{cc}
}

func (c *assessmentServiceClient) CreateAssessment(ctx context.Context, in *CreateAssessmentRequest, opts ...grpc.CallOption) (*Assessment, error) {
	out := new(Assessment)
	err := c.cc.Invoke(ctx, AssessmentService_CreateAssessment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetAssessment(ctx context.Context, in *GetAssessmentRequest, opts ...grpc.CallOption) (*Assessment, error) {
	out := new(Assessment)
	err := c.cc.Invoke(ctx, AssessmentService_GetAssessment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) SubmitAssessment(ctx context.Context, in *SubmitAssessmentRequest, opts ...grpc.CallOption) (*SubmissionResponse, error) {
	out := new(SubmissionResponse)
	err := c.cc.Invoke(ctx, AssessmentService_SubmitAssessment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessmentServiceClient) GetGrade(ctx context.Context, in *GetGradeRequest, opts ...grpc.CallOption) (*GradeResponse, error) {
	out := new(GradeResponse)
	err := c.cc.Invoke(ctx, AssessmentService_GetGrade_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssessmentServiceServer is the server API for AssessmentService service.
// All implementations must embed UnimplementedAssessmentServiceServer
// for forward compatibility
type AssessmentServiceServer interface {
	CreateAssessment(context.Context, *CreateAssessmentRequest) (*Assessment, error)
	GetAssessment(context.Context, *GetAssessmentRequest) (*Assessment, error)
	SubmitAssessment(context.Context, *SubmitAssessmentRequest) (*SubmissionResponse, error)
	GetGrade(context.Context, *GetGradeRequest) (*GradeResponse, error)
	mustEmbedUnimplementedAssessmentServiceServer()
}

// UnimplementedAssessmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAssessmentServiceServer struct {
}

func (UnimplementedAssessmentServiceServer) CreateAssessment(context.Context, *CreateAssessmentRequest) (*Assessment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAssessment not implemented")
}
func (UnimplementedAssessmentServiceServer) GetAssessment(context.Context, *GetAssessmentRequest) (*Assessment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssessment not implemented")
}
func (UnimplementedAssessmentServiceServer) SubmitAssessment(context.Context, *SubmitAssessmentRequest) (*SubmissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAssessment not implemented")
}
func (UnimplementedAssessmentServiceServer) GetGrade(context.Context, *GetGradeRequest) (*GradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGrade not implemented")
}
func (UnimplementedAssessmentServiceServer) mustEmbedUnimplementedAssessmentServiceServer() {}

// UnsafeAssessmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssessmentServiceServer will
// result in compilation errors.
type UnsafeAssessmentServiceServer interface {
	mustEmbedUnimplementedAssessmentServiceServer()
}

func RegisterAssessmentServiceServer(s grpc.ServiceRegistrar, srv AssessmentServiceServer) {
	s.RegisterService(&AssessmentService_ServiceDesc, srv)
}

func _AssessmentService_CreateAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).CreateAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_CreateAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).CreateAssessment(ctx, req.(*CreateAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetAssessment(ctx, req.(*GetAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_SubmitAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).SubmitAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_SubmitAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).SubmitAssessment(ctx, req.(*SubmitAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessmentService_GetGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentServiceServer).GetGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessmentService_GetGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentServiceServer).GetGrade(ctx, req.(*GetGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssessmentService_ServiceDesc is the grpc.ServiceDesc for AssessmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssessmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assessment.v1.AssessmentService",
	HandlerType: (*AssessmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssessment",
			Handler:    _AssessmentService_CreateAssessment_Handler,
		},
		{
			MethodName: "GetAssessment",
			Handler:    _AssessmentService_GetAssessment_Handler,
		},
		{
			MethodName: "SubmitAssessment",
			Handler:    _AssessmentService_SubmitAssessment_Handler,
		},
		{
			MethodName: "GetGrade",
			Handler:    _AssessmentService_GetGrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/assessment.proto",
}
