// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/notification.proto

package notificationpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPreferences struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailCourseUpdates bool                   `protobuf:"varint,2,opt,name=email_course_updates,json=emailCourseUpdates,proto3" json:"email_course_updates,omitempty"`
	EmailMarketing     bool                   `protobuf:"varint,3,opt,name=email_marketing,json=emailMarketing,proto3" json:"email_marketing,omitempty"`
	InAppMentions      bool                   `protobuf:"varint,4,opt,name=in_app_mentions,json=inAppMentions,proto3" json:"in_app_mentions,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *UserPreferences) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPreferences) GetEmailCourseUpdates() bool {
	if x != nil {
		return x.EmailCourseUpdates
	}
	return false
}

func (x *UserPreferences) GetEmailMarketing() bool {
	if x != nil {
		return x.EmailMarketing
	}
	return false
}

func (x *UserPreferences) GetInAppMentions() bool {
	if x != nil {
		return x.InAppMentions
	}
	return false
}

func (x *UserPreferences) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdatePreferencesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailCourseUpdates bool                   `protobuf:"varint,2,opt,name=email_course_updates,json=emailCourseUpdates,proto3" json:"email_course_updates,omitempty"`
	EmailMarketing     bool                   `protobuf:"varint,3,opt,name=email_marketing,json=emailMarketing,proto3" json:"email_marketing,omitempty"`
	InAppMentions      bool                   `protobuf:"varint,4,opt,name=in_app_mentions,json=inAppMentions,proto3" json:"in_app_mentions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetEmailCourseUpdates() bool {
	if x != nil {
		return x.EmailCourseUpdates
	}
	return false
}

func (x *UpdatePreferencesRequest) GetEmailMarketing() bool {
	if x != nil {
		return x.EmailMarketing
	}
	return false
}

func (x *UpdatePreferencesRequest) GetInAppMentions() bool {
	if x != nil {
		return x.InAppMentions
	}
	return false
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   *UserPreferences       `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferencesResponse) Reset() {
	*x = PreferencesResponse{}
	mi := &file_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferencesResponse) ProtoMessage() {}

func (x *PreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferencesResponse.ProtoReflect.Descriptor instead.
func (*PreferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *PreferencesResponse) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

var File_proto_notification_proto protoreflect.FileDescriptor

const file_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x18proto/notification.proto\x12\x0fnotification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xe8\x01\n" +
	"\x0fUserPreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x14email_course_updates\x18\x02 \x01(\bR\x12emailCourseUpdates\x12'\n" +
	"\x0femail_marketing\x18\x03 \x01(\bR\x0eemailMarketing\x12&\n" +
	"\x0fin_app_mentions\x18\x04 \x01(\bR\rinAppMentions\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb6\x01\n" +
	"\x18UpdatePreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x14email_course_updates\x18\x02 \x01(\bR\x12emailCourseUpdates\x12'\n" +
	"\x0femail_marketing\x18\x03 \x01(\bR\x0eemailMarketing\x12&\n" +
	"\x0fin_app_mentions\x18\x04 \x01(\bR\rinAppMentions\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\x13PreferencesResponse\x12B\n" +
	"\vpreferences\x18\x01 \x01(\v2 .notification.v1.UserPreferencesR\vpreferences2\xb6\x02\n" +
	"\x13NotificationService\x12\x92\x01\n" +
	"\x11UpdatePreferences\x12).notification.v1.UpdatePreferencesRequest\x1a$.notification.v1.PreferencesResponse\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/v1/notifications/preferences\x12\x89\x01\n" +
	"\x0eGetPreferences\x12&.notification.v1.GetPreferencesRequest\x1a$.notification.v1.PreferencesResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/notifications/preferencesBEZCgithub.com/amnayem/skillforge/shared/pb/notification;notificationpbb\x06proto3"

var (
	file_proto_notification_proto_rawDescOnce sync.Once
	file_proto_notification_proto_rawDescData []byte
)

func file_proto_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)))
	})
	return file_proto_notification_proto_rawDescData
}

var file_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_notification_proto_goTypes = []any{
	(*UserPreferences)(nil),          // 0: notification.v1.UserPreferences
	(*UpdatePreferencesRequest)(nil), // 1: notification.v1.UpdatePreferencesRequest
	(*GetPreferencesRequest)(nil),    // 2: notification.v1.GetPreferencesRequest
	(*PreferencesResponse)(nil),      // 3: notification.v1.PreferencesResponse
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_proto_notification_proto_depIdxs = []int32{
	4, // 0: notification.v1.UserPreferences.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: notification.v1.PreferencesResponse.preferences:type_name -> notification.v1.UserPreferences
	1, // 2: notification.v1.NotificationService.UpdatePreferences:input_type -> notification.v1.UpdatePreferencesRequest
	2, // 3: notification.v1.NotificationService.GetPreferences:input_type -> notification.v1.GetPreferencesRequest
	3, // 4: notification.v1.NotificationService.UpdatePreferences:output_type -> notification.v1.PreferencesResponse
	3, // 5: notification.v1.NotificationService.GetPreferences:output_type -> notification.v1.PreferencesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_notification_proto_init() }
func file_proto_notification_proto_init() {
	if File_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_proto_rawDesc), len(file_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_proto_depIdxs,
		MessageInfos:      file_proto_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_proto = out.File
	file_proto_notification_proto_goTypes = nil
	file_proto_notification_proto_depIdxs = nil
}
