// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tenant.proto

package tenantpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	AdminEmail    string                 `protobuf:"bytes,3,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_proto_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateTenantRequest) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_proto_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *GetTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type UpdateTenantSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Theme         string                 `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	FeatureFlags  map[string]string      `protobuf:"bytes,4,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantSettingsRequest) Reset() {
	*x = UpdateTenantSettingsRequest{}
	mi := &file_proto_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantSettingsRequest) ProtoMessage() {}

func (x *UpdateTenantSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTenantSettingsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateTenantSettingsRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UpdateTenantSettingsRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *UpdateTenantSettingsRequest) GetFeatureFlags() map[string]string {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Theme         string                 `protobuf:"bytes,5,opt,name=theme,proto3" json:"theme,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_proto_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *TenantResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TenantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantResponse) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *TenantResponse) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *TenantResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_proto_tenant_proto protoreflect.FileDescriptor

const file_proto_tenant_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tenant.proto\x12\x12learnhub.tenant.v1\"b\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1f\n" +
	"\vadmin_email\x18\x03 \x01(\tR\n" +
	"adminEmail\"/\n" +
	"\x10GetTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\x94\x02\n" +
	"\x1bUpdateTenantSettingsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\x12\x19\n" +
	"\blogo_url\x18\x03 \x01(\tR\alogoUrl\x12f\n" +
	"\rfeature_flags\x18\x04 \x03(\v2A.learnhub.tenant.v1.UpdateTenantSettingsRequest.FeatureFlagsEntryR\ffeatureFlags\x1a?\n" +
	"\x11FeatureFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x0eTenantResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05theme\x18\x05 \x01(\tR\x05theme\x12\x19\n" +
	"\blogo_url\x18\x06 \x01(\tR\alogoUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt2\xb0\x02\n" +
	"\rTenantService\x12[\n" +
	"\fCreateTenant\x12'.learnhub.tenant.v1.CreateTenantRequest\x1a\".learnhub.tenant.v1.TenantResponse\x12U\n" +
	"\tGetTenant\x12$.learnhub.tenant.v1.GetTenantRequest\x1a\".learnhub.tenant.v1.TenantResponse\x12k\n" +
	"\x14UpdateTenantSettings\x12/.learnhub.tenant.v1.UpdateTenantSettingsRequest\x1a\".learnhub.tenant.v1.TenantResponseB2Z0github.com/amnayem/skillforge/shared/pb/tenantpbb\x06proto3"

var (
	file_proto_tenant_proto_rawDescOnce sync.Once
	file_proto_tenant_proto_rawDescData []byte
)

func file_proto_tenant_proto_rawDescGZIP() []byte {
	file_proto_tenant_proto_rawDescOnce.Do(func() {
		file_proto_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tenant_proto_rawDesc), len(file_proto_tenant_proto_rawDesc)))
	})
	return file_proto_tenant_proto_rawDescData
}

var file_proto_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tenant_proto_goTypes = []any{
	(*CreateTenantRequest)(nil),         // 0: learnhub.tenant.v1.CreateTenantRequest
	(*GetTenantRequest)(nil),            // 1: learnhub.tenant.v1.GetTenantRequest
	(*UpdateTenantSettingsRequest)(nil), // 2: learnhub.tenant.v1.UpdateTenantSettingsRequest
	(*TenantResponse)(nil),              // 3: learnhub.tenant.v1.TenantResponse
	nil,                                 // 4: learnhub.tenant.v1.UpdateTenantSettingsRequest.FeatureFlagsEntry
}
var file_proto_tenant_proto_depIdxs = []int32{
	4, // 0: learnhub.tenant.v1.UpdateTenantSettingsRequest.feature_flags:type_name -> learnhub.tenant.v1.UpdateTenantSettingsRequest.FeatureFlagsEntry
	0, // 1: learnhub.tenant.v1.TenantService.CreateTenant:input_type -> learnhub.tenant.v1.CreateTenantRequest
	1, // 2: learnhub.tenant.v1.TenantService.GetTenant:input_type -> learnhub.tenant.v1.GetTenantRequest
	2, // 3: learnhub.tenant.v1.TenantService.UpdateTenantSettings:input_type -> learnhub.tenant.v1.UpdateTenantSettingsRequest
	3, // 4: learnhub.tenant.v1.TenantService.CreateTenant:output_type -> learnhub.tenant.v1.TenantResponse
	3, // 5: learnhub.tenant.v1.TenantService.GetTenant:output_type -> learnhub.tenant.v1.TenantResponse
	3, // 6: learnhub.tenant.v1.TenantService.UpdateTenantSettings:output_type -> learnhub.tenant.v1.TenantResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tenant_proto_init() }
func file_proto_tenant_proto_init() {
	if File_proto_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tenant_proto_rawDesc), len(file_proto_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tenant_proto_goTypes,
		DependencyIndexes: file_proto_tenant_proto_depIdxs,
		MessageInfos:      file_proto_tenant_proto_msgTypes,
	}.Build()
	File_proto_tenant_proto = out.File
	file_proto_tenant_proto_goTypes = nil
	file_proto_tenant_proto_depIdxs = nil
}
